### ISSUE TITLE
old example position file in Demos/Multi-Modal

### ISSUE THREAD

**Issue by asalmon91** [BrainardLab/AOAutomontaging#3]
[MODERN_ExamplePositionFile.xlsx](https://github.com/BrainardLab/AOAutomontaging/files/2229179/MODERN_ExamplePositionFile.xlsx)

The example position file in the demo is the old version, ran it with the attached file with no problems.

**Comment by Eurybiadan** [comment]
Hey @asalmon91, good catch. If you make the change to the file in a fork of this repo and submit a pull request we can get that fix integrated.

**Comment by Eurybiadan** [comment]
Fixed in 096e835.
